// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Api.Data;

#nullable disable

namespace Webshop.Api.Migrations
{
    [DbContext(typeof(WebshopDbContext))]
    [Migration("20250806062422_SeedProducts3")]
    partial class SeedProducts3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Webshop.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ceramic mug for hot drinks",
                            ImageUrl = "https://via.placeholder.com/300x200.png?text=Product",
                            Name = "Coffee Mug",
                            Price = 49.95m
                        },
                        new
                        {
                            Id = 2,
                            Description = "100% cotton, unisex",
                            ImageUrl = "https://via.placeholder.com/300x200.png?text=Product",
                            Name = "T-Shirt",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A5 notebook with grid paper",
                            ImageUrl = "https://via.placeholder.com/300x200.png?text=Product",
                            Name = "Notebook",
                            Price = 39.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
