name: Deploy Backend

on:
  push:
    branches:
      - main  # or your active branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish API
      run: dotnet publish api/Webshop.Api/Webshop.Api.csproj -c Release -o publish

    - name: Copy to server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: publish/
        target: ${{ secrets.SERVER_BACKEND_PATH }}

    - name: Remove old SQLite DB and restart backend
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Stop the API
          sudo systemctl stop webshop-api.service
          
          # Remove the existing SQLite DB (adjust name/path if different)
          sudo rm -f ${{ secrets.SERVER_BACKEND_PATH }}/app.db

          # Restart the API (will recreate DB via migrations)
          sudo systemctl start webshop-api.service
